name: "❓ Other"
description: Anything else that is not a feature request or bug report.
labels: [ ":question: Other" ]
body:
  - type: markdown
    attributes:
      value: |
        **Before You Start...**
        
        This form is for anything else that is not a feature requests or bug. 
        
        Try to search for your issue - it may have already been answered.
        However, if you find that an old, closed issue still persists in the latest version,
        you should open a new issue using the form below instead of commenting on the old issue.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: |
        Clear and concise question to get help ASAP. Note that you can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format lists and code.
      placeholder: Steps to reproduce
    validations:
      required: true